apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          {{- if .Values.externalSecret.enabled }}
          env:
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: rok-general-secret
                  key: SECRET_MESSAGE
          {{- end }}
          readinessProbe:
            httpGet: { path: /healthz, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
