apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: "2.11.0"
  targetNamespace: external-secrets
  createNamespace: true
  valuesContent: |-
    installCRDs: true
    extraEnv:
      - name: AWS_ENDPOINT_URL
        value: "http://192.168.122.1:4566"
      - name: AWS_ENDPOINT_URL_SECRETS_MANAGER
        value: "http://192.168.122.1:4566"
      - name: AWS_REGION
        value: "us-east-1"
